.TH LIBQUADTREE "3" "April 12th, 2012" "libquadtree 1.1" "libquadtree - Fast quadtree implementation"

.SH NAME
libquadtree - Fast quadtree library
.SH SYNOPSIS
.B #include <quadtree.h>
.sp
.BI "UFQuadTree *qt_create_quadtree(Quadrant *" region ",
.BI                                 BUCKETSIZE " maxfill ");
.SH DESCRIPTION
The quadtree library is...
.SH EXAMPLE
.SH AUTHORS
Written at Lokku ltd <opensource@lokku.com>

.SH COPYRIGHT
Copyright (C) 2011-2012 Lokku ltd. and contributors
.P
License: GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
Project homepage:  <https://www.github.com/darksmo/quadtree>
.br
Lokku:  <http://www.lokku.com/>
